---
- hosts: ubuntu
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=true

    - name: start the service
      service: name=nginx state=started enabled=true
